#!/usr/bin/env python3
"""Generate font5x7.h (printable ASCII 0x20..0x7E) from Adafruit_GFX glcdfont.c.

Why this generator exists
-------------------------
The UI needs a tiny monochrome font and the firmware deliberately avoids pulling
in a full graphics library (Adafruit_GFX / GxEPD2 / LVGL) for four screens.
Hand-typing a 5x7 font table is error prone, so the table is generated
mechanically from the *classic* 5x7 bitmap font that ships with Adafruit_GFX
(`glcdfont.c`, 5 bytes per glyph, column major, bit 0 = top row).

The generated header is committed, so building the firmware never needs this
script or the Adafruit library; the script only documents provenance and lets
the table be regenerated.

Usage:
    python3 tools/gen_font5x7.py \
        "$HOME/Documents/Arduino/libraries/Adafruit_GFX_Library/glcdfont.c" \
        font5x7.h
"""

import re
import sys

FIRST_CHAR = 0x20
LAST_CHAR = 0x7E
GLYPH_BYTES = 5


def load_font(path):
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    # Keep only the initializer of `static const unsigned char font[] PROGMEM = {...}`
    match = re.search(r"font\[\]\s*PROGMEM\s*=\s*\{(.*?)\};", text, re.S)
    if match is None:
        raise SystemExit("could not find the font[] table in %s" % path)
    values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{2})", match.group(1))]
    expected = 256 * GLYPH_BYTES
    if len(values) < expected:
        raise SystemExit("expected at least %d bytes, got %d" % (expected, len(values)))
    return values


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    font = load_font(src)

    count = LAST_CHAR - FIRST_CHAR + 1
    rows = []
    for index in range(count):
        char_code = FIRST_CHAR + index
        base = char_code * GLYPH_BYTES
        glyph = font[base:base + GLYPH_BYTES]
        rows.append("    " + " ".join("0x%02X," % b for b in glyph))

    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Generated by tools/gen_font5x7.py -- do not edit by hand.")
    lines.append("//")
    lines.append("// Classic 5x7 bitmap font shipped with Adafruit_GFX (glcdfont.c),")
    lines.append("// restricted to printable ASCII 0x20..0x7E.")
    lines.append("//")
    lines.append("// Layout per glyph: 5 bytes, column major, one byte per column,")
    lines.append("// bit 0 = top row .. bit 6 = bottom row. Advance is 6 px (5 + 1 gap).")
    lines.append("// Attribution is recorded in THIRD_PARTY_NOTICES.md.")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace voice_memo_ui {")
    lines.append("")
    lines.append("constexpr uint8_t kFontFirstChar = 0x%02X;" % FIRST_CHAR)
    lines.append("constexpr uint8_t kFontLastChar = 0x%02X;" % LAST_CHAR)
    lines.append("constexpr uint8_t kFontGlyphWidth = 5;")
    lines.append("constexpr uint8_t kFontGlyphHeight = 7;")
    lines.append("constexpr uint8_t kFontGlyphAdvance = 6;")
    lines.append("")
    lines.append("constexpr uint8_t kFont5x7[] = {")
    lines.extend(rows)
    lines.append("};")
    lines.append("")
    lines.append("constexpr uint16_t kFont5x7Bytes = sizeof(kFont5x7);")
    lines.append("")
    lines.append("}  // namespace voice_memo_ui")
    lines.append("")

    with open(dst, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    print("wrote %s (%d glyphs, %d bytes)" % (dst, count, count * GLYPH_BYTES))


if __name__ == "__main__":
    main()
