#!/usr/bin/env python3
"""Generate epd_waveform_tables.h from the official Waveshare EPD driver.

The 1.54inch 200x200 panel needs two 159 byte waveform (LUT) tables: one for the
full refresh and one for the partial refresh. They are copied byte-for-byte from
the official Waveshare demo for this exact product:

    waveshareteam/ESP32-S3-ePaper-1.54
    02_Example/Arduino/09_LVGL_V8_Test/src/display/epaper_driver_bsp.cpp
      const uint8_t WF_Full_1IN54[159]
      unsigned char WF_PARTIAL_1IN54_0[159]

Copying them mechanically removes any chance of a transcription error in a
firmware that cannot be visually diffed against the original.

Usage:
    python3 tools/gen_epd_waveform.py <path-to-epaper_driver_bsp.cpp> epd_waveform_tables.h
"""

import re
import sys

TABLES = [
    ("WF_Full_1IN54", "kWaveformFull"),
    ("WF_PARTIAL_1IN54_0", "kWaveformPartial"),
]
EXPECTED_BYTES = 159
PER_LINE = 12


def extract(path, symbol):
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    match = re.search(r"%s\s*\[\s*(\d+)\s*\]\s*=\s*\{(.*?)\};" % symbol, text, re.S)
    if match is None:
        raise SystemExit("symbol %s not found in %s" % (symbol, path))
    declared = int(match.group(1))
    values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]+)", match.group(2))]
    if declared != len(values):
        raise SystemExit("%s: declared %d entries but found %d" % (symbol, declared, len(values)))
    return values


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/gen_epd_waveform.py -- do not edit by hand.",
        "//",
        "// Waveform (LUT) tables for the 1.54inch 200x200 e-paper panel, copied",
        "// byte for byte from the official Waveshare driver:",
        "//   waveshareteam/ESP32-S3-ePaper-1.54",
        "//   02_Example/Arduino/09_LVGL_V8_Test/src/display/epaper_driver_bsp.cpp",
        "//",
        "// kWaveformFull    <- WF_Full_1IN54      (159 bytes, full refresh)",
        "// kWaveformPartial <- WF_PARTIAL_1IN54_0 (159 bytes, partial refresh)",
        "//",
        "// Attribution is recorded in THIRD_PARTY_NOTICES.md.",
        "",
        "#include <cstdint>",
        "",
        "namespace voice_memo_ui {",
        "",
    ]

    for symbol, name in TABLES:
        values = extract(src, symbol)
        if len(values) != EXPECTED_BYTES:
            raise SystemExit("%s: expected %d bytes, got %d" % (symbol, EXPECTED_BYTES, len(values)))
        lines.append("constexpr uint8_t %s[%d] = {  // %s" % (name, len(values), symbol))
        for start in range(0, len(values), PER_LINE):
            chunk = values[start:start + PER_LINE]
            lines.append("    " + " ".join("0x%02X," % v for v in chunk))
        lines.append("};")
        lines.append("")

    lines.append("}  // namespace voice_memo_ui")
    lines.append("")

    with open(dst, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print("wrote %s" % dst)


if __name__ == "__main__":
    main()
